### ISSUE TITLE
Colaborador del repositorio

### ISSUE THREAD

**Issue by BrayanFSanchez** [julio0188/scripting#1]
Hola, 

me gustaría solicitar ser colaborador de tu repositorio para agregar mi parte del proyecto. 

Saludos

**Comment by julio0188** [comment]
Listo

**Comment by BrayanFSanchez** [comment]
De momento no me permite enviar commits, me aparece el siguiente error:

remote: Permission to julio0188/scripting.git denied to BrayanFSanchez.
fatal: unable to access 'https://github.com/julio0188/scripting.git/': The requested URL returned error: 403

**Comment by julio0188** [comment]
Perdón, solo escribí el listo pero no te había agregado, ya te agregué, podes validar nuevamente porfa

**Comment by BrayanFSanchez** [comment]
Todo bien, ya logre enviar mi parte, gracias.
